name: Terraform Validate

on:
  push:
    paths:
      - 'Terraform/**/*.tf'
      - 'Terraform/.github/workflows/terraform-validate.yml'
  pull_request:
    paths:
      - 'Terraform/**/*.tf'
      - 'Terraform/.github/workflows/terraform-validate.yml'

jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.15.7

      - name: Terraform fmt check
        run: terraform fmt -check -recursive

      - name: Terraform init
        run: terraform init -backend=false

      - name: Terraform validate
        run: terraform validate
